# Generated by Django 5.2.2 on 2025-06-04 19:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True, verbose_name='Название ОП')),
                ('description', models.TextField(blank=True, verbose_name='Описание ОП')),
            ],
            options={
                'verbose_name': 'образовательная программа',
                'verbose_name_plural': 'образовательные программы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +79998887766 (7-15 цифр).', regex='^\\+?\\d{7,15}$')], verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'студент',
                'verbose_name_plural': 'студенты',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField(verbose_name='Год поступления')),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Средний балл (GPA)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_program.educationprogram', verbose_name='Программа')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_program.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'зачисление',
                'verbose_name_plural': 'зачисления',
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('student', 'program', 'start_year'), name='unique_enrollment_per_year')],
            },
        ),
    ]
