# Generated by Django 5.2.2 on 2025-06-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogram',
            name='head_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail академ. руководителя'),
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='head_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Академический руководитель — ФИО'),
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail менеджера'),
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='manager_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Менеджер программы — ФИО'),
        ),
    ]
