# Generated by Django 5.2.2 on 2025-06-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_program', '0002_educationprogram_head_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='group',
            field=models.CharField(blank=True, max_length=20, verbose_name='Учебная группа'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Учится'), ('academic_leave', 'Академический отпуск'), ('expelled', 'Отчислен')], default='active', max_length=15, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='study_form',
            field=models.CharField(choices=[('full_time', 'Очная'), ('part_time', 'Очно-заочная')], default='full_time', max_length=15, verbose_name='Форма обучения'),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
